import crypto from 'crypto';
import {query} from '../config/db.js';
const endpoint='https://api.paystack.co';
function enabled(){return process.env.PAYMENT_PROVIDER==='paystack'&&process.env.PAYSTACK_SECRET_KEY}
async function request(path,options={}){const r=await fetch(endpoint+path,{...options,headers:{Authorization:`Bearer ${process.env.PAYSTACK_SECRET_KEY}`,'Content-Type':'application/json',...(options.headers||{})}});const body=await r.json();if(!r.ok||!body.status)throw new Error(body.message||'Payment provider request failed');return body.data}
export const paymentService={
 async initializePayment(order,email){if(!enabled())throw Object.assign(new Error('Online payments are not configured yet'),{status:503});const reference=`LSY-${order.id}-${crypto.randomUUID().replaceAll('-','').slice(0,16)}`;const data=await request('/transaction/initialize',{method:'POST',body:JSON.stringify({email,amount:Math.round(Number(order.total)*100),currency:process.env.STORE_CURRENCY||'NGN',reference,callback_url:`${process.env.CLIENT_URL}/payment/callback?reference=${reference}`,metadata:{order_id:order.id}})});await query("INSERT INTO payments(order_id,provider,reference,status,amount) VALUES($1,'paystack',$2,'pending',$3)",[order.id,reference,order.total]);return {reference,authorizationUrl:data.authorization_url};},
 async verifyPayment(reference){if(!enabled())throw Object.assign(new Error('Online payments are not configured yet'),{status:503});const data=await request('/transaction/verify/'+encodeURIComponent(reference));const payment=(await query('SELECT * FROM payments WHERE reference=$1',[reference])).rows[0];if(!payment)throw Object.assign(new Error('Payment not found'),{status:404});if(data.status==='success'&&Number(data.amount)===Math.round(Number(payment.amount)*100)){await query("UPDATE payments SET status='paid' WHERE id=$1",[payment.id]);await query("UPDATE orders SET payment_status='paid',status='paid' WHERE id=$1",[payment.order_id]);return {paid:true,orderId:payment.order_id};}return {paid:false,orderId:payment.order_id};},
 validWebhook(signature,body){return signature===crypto.createHmac('sha512',process.env.PAYSTACK_SECRET_KEY||'').update(body).digest('hex')}
};
