CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE TABLE IF NOT EXISTS users(id SERIAL PRIMARY KEY,name VARCHAR(100) NOT NULL,email VARCHAR(255) UNIQUE NOT NULL,password_hash TEXT NOT NULL,role VARCHAR(20) NOT NULL DEFAULT 'customer' CHECK(role IN('customer','employee','admin')),phone VARCHAR(50),created_at TIMESTAMPTZ DEFAULT now());
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_role_check; ALTER TABLE users ADD CONSTRAINT users_role_check CHECK(role IN('customer','employee','admin'));
CREATE TABLE IF NOT EXISTS password_reset_tokens(id SERIAL PRIMARY KEY,user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,token_hash TEXT NOT NULL UNIQUE,expires_at TIMESTAMPTZ NOT NULL,used_at TIMESTAMPTZ,created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS store_settings(id SMALLINT PRIMARY KEY DEFAULT 1 CHECK(id=1),data JSONB NOT NULL DEFAULT '{}'::jsonb,updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS categories(id SERIAL PRIMARY KEY,name VARCHAR(100) UNIQUE NOT NULL,slug VARCHAR(120) UNIQUE NOT NULL,active BOOLEAN DEFAULT true,created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS products(id SERIAL PRIMARY KEY,category_id INT NOT NULL REFERENCES categories(id) ON DELETE RESTRICT,name VARCHAR(255) NOT NULL,description TEXT NOT NULL DEFAULT '',price NUMERIC(12,2) NOT NULL CHECK(price>=0),discount_price NUMERIC(12,2) CHECK(discount_price>=0),stock INT NOT NULL DEFAULT 0 CHECK(stock>=0),sku VARCHAR(100) UNIQUE NOT NULL,brand VARCHAR(100),featured BOOLEAN DEFAULT false,new_arrival BOOLEAN DEFAULT false,best_seller BOOLEAN DEFAULT false,active BOOLEAN DEFAULT true,rating NUMERIC(2,1) DEFAULT 0,created_at TIMESTAMPTZ DEFAULT now(),updated_at TIMESTAMPTZ DEFAULT now());
CREATE INDEX IF NOT EXISTS products_search ON products USING gin((name||' '||description||' '||sku) gin_trgm_ops); CREATE INDEX IF NOT EXISTS products_category ON products(category_id);
CREATE TABLE IF NOT EXISTS product_images(id SERIAL PRIMARY KEY,product_id INT REFERENCES products(id) ON DELETE CASCADE,url TEXT NOT NULL,alt TEXT,position INT DEFAULT 0);
CREATE TABLE IF NOT EXISTS product_variants(id SERIAL PRIMARY KEY,product_id INT REFERENCES products(id) ON DELETE CASCADE,name VARCHAR(100) NOT NULL,options JSONB NOT NULL DEFAULT '{}',price NUMERIC(12,2),stock INT CHECK(stock>=0),sku VARCHAR(100) UNIQUE);
CREATE TABLE IF NOT EXISTS addresses(id SERIAL PRIMARY KEY,user_id INT REFERENCES users(id) ON DELETE CASCADE,name TEXT,phone TEXT,country TEXT,region TEXT,city TEXT,address TEXT,postal_code TEXT);
CREATE TABLE IF NOT EXISTS carts(id SERIAL PRIMARY KEY,user_id INT UNIQUE REFERENCES users(id) ON DELETE CASCADE,created_at TIMESTAMPTZ DEFAULT now()); CREATE TABLE IF NOT EXISTS cart_items(id SERIAL PRIMARY KEY,cart_id INT REFERENCES carts(id) ON DELETE CASCADE,product_id INT REFERENCES products(id) ON DELETE CASCADE,variant_id INT REFERENCES product_variants(id) ON DELETE SET NULL,quantity INT CHECK(quantity>0),UNIQUE(cart_id,product_id,variant_id));
CREATE TABLE IF NOT EXISTS orders(id SERIAL PRIMARY KEY,user_id INT REFERENCES users(id) ON DELETE SET NULL,status VARCHAR(30) NOT NULL DEFAULT 'pending_payment',payment_status VARCHAR(30) NOT NULL DEFAULT 'pending',subtotal NUMERIC(12,2) NOT NULL,shipping_cost NUMERIC(12,2) NOT NULL DEFAULT 0,total NUMERIC(12,2) NOT NULL,shipping_address JSONB NOT NULL,tracking_number TEXT,created_at TIMESTAMPTZ DEFAULT now()); CREATE INDEX IF NOT EXISTS orders_user ON orders(user_id,created_at DESC);
CREATE TABLE IF NOT EXISTS order_items(id SERIAL PRIMARY KEY,order_id INT REFERENCES orders(id) ON DELETE CASCADE,product_id INT REFERENCES products(id) ON DELETE SET NULL,variant_id INT REFERENCES product_variants(id) ON DELETE SET NULL,name TEXT NOT NULL,unit_price NUMERIC(12,2) NOT NULL,quantity INT NOT NULL CHECK(quantity>0)); CREATE TABLE IF NOT EXISTS payments(id SERIAL PRIMARY KEY,order_id INT REFERENCES orders(id) ON DELETE CASCADE,provider VARCHAR(30),reference VARCHAR(255) UNIQUE,status VARCHAR(30) DEFAULT 'pending',amount NUMERIC(12,2),created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS reviews(id SERIAL PRIMARY KEY,product_id INT REFERENCES products(id) ON DELETE CASCADE,user_id INT REFERENCES users(id) ON DELETE SET NULL,rating INT CHECK(rating BETWEEN 1 AND 5),body TEXT,approved BOOLEAN DEFAULT false,created_at TIMESTAMPTZ DEFAULT now(),UNIQUE(product_id,user_id)); CREATE TABLE IF NOT EXISTS comments(id SERIAL PRIMARY KEY,product_id INT REFERENCES products(id) ON DELETE CASCADE,user_id INT REFERENCES users(id) ON DELETE SET NULL,body TEXT NOT NULL,parent_id INT REFERENCES comments(id) ON DELETE CASCADE,approved BOOLEAN DEFAULT true,created_at TIMESTAMPTZ DEFAULT now()); CREATE TABLE IF NOT EXISTS messages(id SERIAL PRIMARY KEY,user_id INT REFERENCES users(id) ON DELETE SET NULL,name TEXT,email TEXT,body TEXT NOT NULL,reply TEXT,read BOOLEAN DEFAULT false,archived BOOLEAN DEFAULT false,created_at TIMESTAMPTZ DEFAULT now()); CREATE TABLE IF NOT EXISTS shipping_zones(id SERIAL PRIMARY KEY,name TEXT NOT NULL,active BOOLEAN DEFAULT true); CREATE TABLE IF NOT EXISTS shipping_rates(id SERIAL PRIMARY KEY,zone_id INT REFERENCES shipping_zones(id) ON DELETE CASCADE,country_code VARCHAR(2),amount NUMERIC(12,2) NOT NULL,free_shipping_threshold NUMERIC(12,2),estimated_days VARCHAR(50));

