import {Router} from 'express'; import bcrypt from 'bcryptjs'; import jwt from 'jsonwebtoken'; import crypto from 'crypto'; import {z} from 'zod'; import {query} from '../config/db.js'; import {sendPasswordResetEmail} from '../services/email.service.js';
const r=Router(), credentials=z.object({email:z.string().email(),password:z.string().min(8),name:z.string().min(2).max(100).optional()});
const token=(u)=>jwt.sign({id:u.id,role:u.role},process.env.JWT_SECRET,{expiresIn:'7d'});
r.post('/register',async(req,res,next)=>{try{const v=credentials.parse(req.body); const hash=await bcrypt.hash(v.password,12); const x=await query('INSERT INTO users(name,email,password_hash) VALUES($1,$2,$3) RETURNING id,name,email,role',[v.name||'Customer',v.email.toLowerCase(),hash]); res.status(201).json({user:x.rows[0],token:token(x.rows[0])})}catch(e){next(e)}});
r.post('/login',async(req,res,next)=>{try{const v=credentials.pick({email:true,password:true}).parse(req.body);const x=await query('SELECT * FROM users WHERE email=$1',[v.email.toLowerCase()]);if(!x.rowCount||!await bcrypt.compare(v.password,x.rows[0].password_hash)) return res.status(401).json({message:'Invalid email or password'}); const u=x.rows[0];res.json({user:{id:u.id,name:u.name,email:u.email,role:u.role},token:token(u)})}catch(e){next(e)}});
r.get('/me',async(req,res,next)=>{try{const t=req.headers.authorization?.replace('Bearer ','');if(!t)return res.status(401).end();const p=jwt.verify(t,process.env.JWT_SECRET);const x=await query('SELECT id,name,email,role FROM users WHERE id=$1',[p.id]);res.json({user:x.rows[0]})}catch(e){next(e)}});
r.post('/forgot-password',async(req,res,next)=>{try{const {email}=z.object({email:z.string().email()}).parse(req.body),u=await query('SELECT id FROM users WHERE email=$1',[email.toLowerCase()]);if(!u.rowCount)return res.json({message:'If that email exists, a reset link will be sent.'});const raw=crypto.randomBytes(32).toString('hex'),hash=crypto.createHash('sha256').update(raw).digest('hex');await query("INSERT INTO password_reset_tokens(user_id,token_hash,expires_at) VALUES($1,$2,now()+interval '30 minutes')",[u.rows[0].id,hash]);await sendPasswordResetEmail({to:email,link:`${process.env.CLIENT_URL}/reset-password?token=${raw}`});res.json({message:'If that email exists, a reset link will be sent.'})}catch(e){next(e)}});
r.post('/reset-password',async(req,res,next)=>{try{const v=z.object({token:z.string().min(20),password:z.string().min(8)}).parse(req.body),hash=crypto.createHash('sha256').update(v.token).digest('hex'),x=await query('SELECT * FROM password_reset_tokens WHERE token_hash=$1 AND used_at IS NULL AND expires_at>now()',[hash]);if(!x.rowCount)return res.status(400).json({message:'This reset link is invalid or expired'});await query('UPDATE users SET password_hash=$1 WHERE id=$2',[await bcrypt.hash(v.password,12),x.rows[0].user_id]);await query('UPDATE password_reset_tokens SET used_at=now() WHERE id=$1',[x.rows[0].id]);res.json({message:'Password updated. You can now sign in.'})}catch(e){next(e)}});
r.post('/logout',(req,res)=>res.status(204).end()); export default r;
