import {Router} from 'express';import {query} from '../config/db.js';import {authenticate,adminOnly} from '../middleware/auth.js';import {z} from 'zod';const r=Router();
r.get('/settings',async(req,res,next)=>{try{const x=await query('SELECT * FROM store_settings ORDER BY id DESC LIMIT 1');res.json(x.rowCount ? x.rows[0] : {store_name:'LinaStyledYou',tag_line:'Premium beauty, delivered worldwide',logo_url:'',contact_email:'kehindelina@gmail.com',phone:'+2348065205096',whatsapp_number:'2348065205096',instagram_url:'https://instagram.com/linachili_linastyledyou',tiktok_url:'https://tiktok.com',whatsapp_message:'Hello! I would like to make an order.',currency:'NGN',shipping_message:'We ship worldwide'});}catch(e){next(e)}});
r.get('/products/:id/reviews',async(req,res,next)=>{try{res.json((await query(`SELECT r.id,r.rating,r.body,r.created_at,u.name FROM reviews r LEFT JOIN users u ON u.id=r.user_id WHERE r.product_id=$1 AND r.approved=true ORDER BY r.created_at DESC`,[req.params.id])).rows)}catch(e){next(e)}});
r.post('/products/:id/reviews',authenticate,async(req,res,next)=>{try{const v=z.object({rating:z.number().int().min(1).max(5),body:z.string().min(3).max(2000)}).parse(req.body);const bought=await query('SELECT 1 FROM order_items oi JOIN orders o ON o.id=oi.order_id WHERE oi.product_id=$1 AND o.user_id=$2 AND o.payment_status=$3',[req.params.id,req.user.id,'paid']);if(!bought.rowCount)return res.status(403).json({message:'Only verified purchasers can review'});const x=await query('INSERT INTO reviews(product_id,user_id,rating,body,approved) VALUES($1,$2,$3,$4,true) ON CONFLICT(product_id,user_id) DO UPDATE SET rating=$3,body=$4,approved=true RETURNING *',[req.params.id,req.user.id,v.rating,v.body]);await query("UPDATE products SET rating=(SELECT ROUND(AVG(rating)::numeric,1) FROM reviews WHERE product_id=$1 AND approved=true) WHERE id=$1",[req.params.id]);res.status(201).json(x.rows[0])}catch(e){next(e)}});
r.get('/products/:id/comments',async(req,res,next)=>{try{res.json((await query('SELECT c.*,u.name FROM comments c LEFT JOIN users u ON u.id=c.user_id WHERE c.product_id=$1 AND c.approved=true ORDER BY c.created_at DESC',[req.params.id])).rows)}catch(e){next(e)}});
r.post('/products/:id/comments',authenticate,async(req,res,next)=>{try{const v=z.object({body:z.string().min(2).max(2000)}).parse(req.body);const x=await query('INSERT INTO comments(product_id,user_id,body) VALUES($1,$2,$3) RETURNING *',[req.params.id,req.user.id,v.body]);res.status(201).json(x.rows[0])}catch(e){next(e)}});
r.post('/messages',async(req,res,next)=>{try{const v=z.object({name:z.string().min(2),email:z.string().email(),body:z.string().min(3).max(3000)}).parse(req.body);const x=await query('INSERT INTO messages(name,email,body) VALUES($1,$2,$3) RETURNING id,created_at',[v.name,v.email,v.body]);res.status(201).json(x.rows[0])}catch(e){next(e)}});r.get('/messages',authenticate,adminOnly,async(req,res,next)=>{try{res.json((await query('SELECT * FROM messages WHERE archived=false ORDER BY created_at DESC')).rows)}catch(e){next(e)}});export default r;



